services:
    jms_aws.base:
        abstract: true
        arguments: [{key: "%jms_aws.key%", secret: "%jms_aws.secret%", certificate_authority: true}]

    jms_aws.s3:
        parent: jms_aws.base
        class: AmazonS3

    jms_aws.cloudfront:
        parent: jms_aws.base
        class: AmazonCloudFront
